import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-themes="light">
            <body className={inter.className}>
                <section className="relative h-screen w-[100%] flex">
                    {/* ในส่วนของ navbar */}
                    <div className="w-1/5 h-full bg-white flex flex-col justify-center items-center">
                        <div className="w-full h-1/2 bg-white border-2 border-gray-100 p-2">
                            <p className="mt-9 ml-10 flex justify-center items-center">
                                <b className="text-orange-500 text-2xl">
                                    Purr&#39;
                                </b>
                                <b className="text-2xl">Coffee</b>
                            </p>
                        </div>
                        <div className="w-full h-1/2 bg-white border-2 border-gray-100 p-2"></div>
                    </div>
                    {/* จบในส่วนของ navbar */}

                    <div className="static flex-1 h-full bg-slate-200">
                        {children}
                    </div>
                </section>
            </body>
        </html>
    );
}

///ถ้าต้องการที่จะจัดคอลัมให้เพิ่ม flex เข้าไป
